services:
  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-a11y-checker:/data/db

  executor:
    container_name: executor
    build:
      context: .
      dockerfile: ./packages/executor/Dockerfile
    restart: unless-stopped
    shm_size: "2gb"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/extension-a11y-checker
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DEBUG="*"
    depends_on:
      - mongo

  web:
    container_name: a11y-checker
    build:
      context: .
      dockerfile: ./packages/web2/Dockerfile
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/extension-a11y-checker
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DEBUG=*
    ports:
      - "3042:3000"
    depends_on:
      - mongo

volumes:
  mongo-data-a11y-checker:
