/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfilesProfileIdTabIdImport } from './routes/profiles.$profileId.$tabId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfilesProfileIdTabIdRoute = ProfilesProfileIdTabIdImport.update({
  id: '/profiles/$profileId/$tabId',
  path: '/profiles/$profileId/$tabId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profiles/$profileId/$tabId': {
      id: '/profiles/$profileId/$tabId'
      path: '/profiles/$profileId/$tabId'
      fullPath: '/profiles/$profileId/$tabId'
      preLoaderRoute: typeof ProfilesProfileIdTabIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profiles/$profileId/$tabId': typeof ProfilesProfileIdTabIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profiles/$profileId/$tabId': typeof ProfilesProfileIdTabIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profiles/$profileId/$tabId': typeof ProfilesProfileIdTabIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profiles/$profileId/$tabId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profiles/$profileId/$tabId'
  id: '__root__' | '/' | '/profiles/$profileId/$tabId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfilesProfileIdTabIdRoute: typeof ProfilesProfileIdTabIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilesProfileIdTabIdRoute: ProfilesProfileIdTabIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profiles/$profileId/$tabId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profiles/$profileId/$tabId": {
      "filePath": "profiles.$profileId.$tabId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
