/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProfilesProfileIdRouteImport } from "./routes/profiles.$profileId"
import { Route as ApiPdfExportProfileIdRouteImport } from "./routes/api/pdf-export.$profileId"
import { Route as ApiWebhooksExtensionAddedRouteImport } from "./routes/api/webhooks/extension-added"
import { Route as ApiWebhooksInstanceRemovedRouteImport } from "./routes/api/webhooks/instance-removed"
import { Route as ApiWebhooksInstanceUpdatedRouteImport } from "./routes/api/webhooks/instance-updated"
import { Route as ApiWebhooksSecretRotatedRouteImport } from "./routes/api/webhooks/secret-rotated"
import { Route as ProfilesProfileIdIndexRouteImport } from "./routes/profiles.$profileId.index"
import { Route as ProfilesProfileIdIssuesRouteImport } from "./routes/profiles.$profileId.issues"
import { Route as ProfilesProfileIdOverviewRouteImport } from "./routes/profiles.$profileId.overview"
import { Route as ProfilesProfileIdSettingsRouteImport } from "./routes/profiles.$profileId.settings"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesProfileIdRoute = ProfilesProfileIdRouteImport.update({
  id: "/profiles/$profileId",
  path: "/profiles/$profileId",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfExportProfileIdRoute = ApiPdfExportProfileIdRouteImport.update({
  id: "/api/pdf-export/$profileId",
  path: "/api/pdf-export/$profileId",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksExtensionAddedRoute =
  ApiWebhooksExtensionAddedRouteImport.update({
    id: "/api/webhooks/extension-added",
    path: "/api/webhooks/extension-added",
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksInstanceRemovedRoute =
  ApiWebhooksInstanceRemovedRouteImport.update({
    id: "/api/webhooks/instance-removed",
    path: "/api/webhooks/instance-removed",
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksInstanceUpdatedRoute =
  ApiWebhooksInstanceUpdatedRouteImport.update({
    id: "/api/webhooks/instance-updated",
    path: "/api/webhooks/instance-updated",
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksSecretRotatedRoute =
  ApiWebhooksSecretRotatedRouteImport.update({
    id: "/api/webhooks/secret-rotated",
    path: "/api/webhooks/secret-rotated",
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfilesProfileIdIndexRoute = ProfilesProfileIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProfilesProfileIdRoute,
} as any)
const ProfilesProfileIdIssuesRoute = ProfilesProfileIdIssuesRouteImport.update({
  id: "/issues",
  path: "/issues",
  getParentRoute: () => ProfilesProfileIdRoute,
} as any)
const ProfilesProfileIdOverviewRoute =
  ProfilesProfileIdOverviewRouteImport.update({
    id: "/overview",
    path: "/overview",
    getParentRoute: () => ProfilesProfileIdRoute,
  } as any)
const ProfilesProfileIdSettingsRoute =
  ProfilesProfileIdSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => ProfilesProfileIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/profiles/$profileId": typeof ProfilesProfileIdRouteWithChildren
  "/api/pdf-export/$profileId": typeof ApiPdfExportProfileIdRoute
  "/api/webhooks/extension-added": typeof ApiWebhooksExtensionAddedRoute
  "/api/webhooks/instance-removed": typeof ApiWebhooksInstanceRemovedRoute
  "/api/webhooks/instance-updated": typeof ApiWebhooksInstanceUpdatedRoute
  "/api/webhooks/secret-rotated": typeof ApiWebhooksSecretRotatedRoute
  "/profiles/$profileId/issues": typeof ProfilesProfileIdIssuesRoute
  "/profiles/$profileId/overview": typeof ProfilesProfileIdOverviewRoute
  "/profiles/$profileId/settings": typeof ProfilesProfileIdSettingsRoute
  "/profiles/$profileId/": typeof ProfilesProfileIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/api/pdf-export/$profileId": typeof ApiPdfExportProfileIdRoute
  "/api/webhooks/extension-added": typeof ApiWebhooksExtensionAddedRoute
  "/api/webhooks/instance-removed": typeof ApiWebhooksInstanceRemovedRoute
  "/api/webhooks/instance-updated": typeof ApiWebhooksInstanceUpdatedRoute
  "/api/webhooks/secret-rotated": typeof ApiWebhooksSecretRotatedRoute
  "/profiles/$profileId/issues": typeof ProfilesProfileIdIssuesRoute
  "/profiles/$profileId/overview": typeof ProfilesProfileIdOverviewRoute
  "/profiles/$profileId/settings": typeof ProfilesProfileIdSettingsRoute
  "/profiles/$profileId": typeof ProfilesProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/profiles/$profileId": typeof ProfilesProfileIdRouteWithChildren
  "/api/pdf-export/$profileId": typeof ApiPdfExportProfileIdRoute
  "/api/webhooks/extension-added": typeof ApiWebhooksExtensionAddedRoute
  "/api/webhooks/instance-removed": typeof ApiWebhooksInstanceRemovedRoute
  "/api/webhooks/instance-updated": typeof ApiWebhooksInstanceUpdatedRoute
  "/api/webhooks/secret-rotated": typeof ApiWebhooksSecretRotatedRoute
  "/profiles/$profileId/issues": typeof ProfilesProfileIdIssuesRoute
  "/profiles/$profileId/overview": typeof ProfilesProfileIdOverviewRoute
  "/profiles/$profileId/settings": typeof ProfilesProfileIdSettingsRoute
  "/profiles/$profileId/": typeof ProfilesProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/profiles/$profileId"
    | "/api/pdf-export/$profileId"
    | "/api/webhooks/extension-added"
    | "/api/webhooks/instance-removed"
    | "/api/webhooks/instance-updated"
    | "/api/webhooks/secret-rotated"
    | "/profiles/$profileId/issues"
    | "/profiles/$profileId/overview"
    | "/profiles/$profileId/settings"
    | "/profiles/$profileId/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/api/pdf-export/$profileId"
    | "/api/webhooks/extension-added"
    | "/api/webhooks/instance-removed"
    | "/api/webhooks/instance-updated"
    | "/api/webhooks/secret-rotated"
    | "/profiles/$profileId/issues"
    | "/profiles/$profileId/overview"
    | "/profiles/$profileId/settings"
    | "/profiles/$profileId"
  id:
    | "__root__"
    | "/"
    | "/profiles/$profileId"
    | "/api/pdf-export/$profileId"
    | "/api/webhooks/extension-added"
    | "/api/webhooks/instance-removed"
    | "/api/webhooks/instance-updated"
    | "/api/webhooks/secret-rotated"
    | "/profiles/$profileId/issues"
    | "/profiles/$profileId/overview"
    | "/profiles/$profileId/settings"
    | "/profiles/$profileId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfilesProfileIdRoute: typeof ProfilesProfileIdRouteWithChildren
  ApiPdfExportProfileIdRoute: typeof ApiPdfExportProfileIdRoute
  ApiWebhooksExtensionAddedRoute: typeof ApiWebhooksExtensionAddedRoute
  ApiWebhooksInstanceRemovedRoute: typeof ApiWebhooksInstanceRemovedRoute
  ApiWebhooksInstanceUpdatedRoute: typeof ApiWebhooksInstanceUpdatedRoute
  ApiWebhooksSecretRotatedRoute: typeof ApiWebhooksSecretRotatedRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profiles/$profileId": {
      id: "/profiles/$profileId"
      path: "/profiles/$profileId"
      fullPath: "/profiles/$profileId"
      preLoaderRoute: typeof ProfilesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/pdf-export/$profileId": {
      id: "/api/pdf-export/$profileId"
      path: "/api/pdf-export/$profileId"
      fullPath: "/api/pdf-export/$profileId"
      preLoaderRoute: typeof ApiPdfExportProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/webhooks/extension-added": {
      id: "/api/webhooks/extension-added"
      path: "/api/webhooks/extension-added"
      fullPath: "/api/webhooks/extension-added"
      preLoaderRoute: typeof ApiWebhooksExtensionAddedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/webhooks/instance-removed": {
      id: "/api/webhooks/instance-removed"
      path: "/api/webhooks/instance-removed"
      fullPath: "/api/webhooks/instance-removed"
      preLoaderRoute: typeof ApiWebhooksInstanceRemovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/webhooks/instance-updated": {
      id: "/api/webhooks/instance-updated"
      path: "/api/webhooks/instance-updated"
      fullPath: "/api/webhooks/instance-updated"
      preLoaderRoute: typeof ApiWebhooksInstanceUpdatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/webhooks/secret-rotated": {
      id: "/api/webhooks/secret-rotated"
      path: "/api/webhooks/secret-rotated"
      fullPath: "/api/webhooks/secret-rotated"
      preLoaderRoute: typeof ApiWebhooksSecretRotatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profiles/$profileId/": {
      id: "/profiles/$profileId/"
      path: "/"
      fullPath: "/profiles/$profileId/"
      preLoaderRoute: typeof ProfilesProfileIdIndexRouteImport
      parentRoute: typeof ProfilesProfileIdRoute
    }
    "/profiles/$profileId/issues": {
      id: "/profiles/$profileId/issues"
      path: "/issues"
      fullPath: "/profiles/$profileId/issues"
      preLoaderRoute: typeof ProfilesProfileIdIssuesRouteImport
      parentRoute: typeof ProfilesProfileIdRoute
    }
    "/profiles/$profileId/overview": {
      id: "/profiles/$profileId/overview"
      path: "/overview"
      fullPath: "/profiles/$profileId/overview"
      preLoaderRoute: typeof ProfilesProfileIdOverviewRouteImport
      parentRoute: typeof ProfilesProfileIdRoute
    }
    "/profiles/$profileId/settings": {
      id: "/profiles/$profileId/settings"
      path: "/settings"
      fullPath: "/profiles/$profileId/settings"
      preLoaderRoute: typeof ProfilesProfileIdSettingsRouteImport
      parentRoute: typeof ProfilesProfileIdRoute
    }
  }
}

interface ProfilesProfileIdRouteChildren {
  ProfilesProfileIdIssuesRoute: typeof ProfilesProfileIdIssuesRoute
  ProfilesProfileIdOverviewRoute: typeof ProfilesProfileIdOverviewRoute
  ProfilesProfileIdSettingsRoute: typeof ProfilesProfileIdSettingsRoute
  ProfilesProfileIdIndexRoute: typeof ProfilesProfileIdIndexRoute
}

const ProfilesProfileIdRouteChildren: ProfilesProfileIdRouteChildren = {
  ProfilesProfileIdIssuesRoute: ProfilesProfileIdIssuesRoute,
  ProfilesProfileIdOverviewRoute: ProfilesProfileIdOverviewRoute,
  ProfilesProfileIdSettingsRoute: ProfilesProfileIdSettingsRoute,
  ProfilesProfileIdIndexRoute: ProfilesProfileIdIndexRoute,
}

const ProfilesProfileIdRouteWithChildren =
  ProfilesProfileIdRoute._addFileChildren(ProfilesProfileIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilesProfileIdRoute: ProfilesProfileIdRouteWithChildren,
  ApiPdfExportProfileIdRoute: ApiPdfExportProfileIdRoute,
  ApiWebhooksExtensionAddedRoute: ApiWebhooksExtensionAddedRoute,
  ApiWebhooksInstanceRemovedRoute: ApiWebhooksInstanceRemovedRoute,
  ApiWebhooksInstanceUpdatedRoute: ApiWebhooksInstanceUpdatedRoute,
  ApiWebhooksSecretRotatedRoute: ApiWebhooksSecretRotatedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { startInstance } from "./start.ts"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
