apiVersion: v1
kind: Secret
metadata:
  name: a11y-checker-secret
type: Opaque
data:
  mongo-uri: {{ printf "mongodb://%s-mongodb:27017/%s" .Release.Name .Values.mongodb.database | b64enc }}
  extension-secret: {{ .Values.extensionSecret | b64enc }}
