apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webApp.name }}
spec:
  selector:
    app: {{ .Values.webApp.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: {{ .Values.webApp.service.type }}
